{
  "formatVersion": "1.1",
  "component": {
    "url": "../../notificationskit/0.2.1.1/notificationskit-0.2.1.1.module",
    "group": "com.pentabit.notificationskit",
    "module": "notificationskit",
    "version": "0.2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "notificationskit.aar",
          "url": "notificationskit-android-0.2.1.1.aar",
          "size": 139740,
          "sha512": "e713a53dcc7c84d72fac2b4988abe7abf97e6c170ad475894d462424c06dc377cc66748f8382247f65c2d211ae772f82516fd1c0992d88d7252addc4beefe772",
          "sha256": "e691e40355f011bda4cf4d104bbf4492fe6d0f0d72542054470591a8ee04d108",
          "sha1": "5eda9584f12c7fd96386613325e4bb0c34d871e8",
          "md5": "1ee6e8ad32b36383f54cff5570a6df4a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "notificationskit.aar",
          "url": "notificationskit-android-0.2.1.1.aar",
          "size": 139740,
          "sha512": "e713a53dcc7c84d72fac2b4988abe7abf97e6c170ad475894d462424c06dc377cc66748f8382247f65c2d211ae772f82516fd1c0992d88d7252addc4beefe772",
          "sha256": "e691e40355f011bda4cf4d104bbf4492fe6d0f0d72542054470591a8ee04d108",
          "sha1": "5eda9584f12c7fd96386613325e4bb0c34d871e8",
          "md5": "1ee6e8ad32b36383f54cff5570a6df4a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "notificationskit-android-0.2.1.1-sources.jar",
          "url": "notificationskit-android-0.2.1.1-sources.jar",
          "size": 40140,
          "sha512": "c188da1d1026339642be584b28f6489eaf98ed87b0c619f4e2f92b5d4956cb49b71ecb7e1c3573f34914f82e2bc324ecd135b76063a49f1af395b5eb6cfa6478",
          "sha256": "f6df29eae65b9534ca670f0191b9c7af081e48e0e8a4f797b82655d48d517d20",
          "sha1": "88f7cf8a895b8c8a18b95b43b8e69c5187b6e98a",
          "md5": "1a6e51d75428a7ecd2247bfe6cea70d1"
        }
      ]
    }
  ]
}
